********* Start testing of tst_ExpectFail *********
Config: Using QTest library @INSERT_QT_VERSION_HERE@, Qt @INSERT_QT_VERSION_HERE@
PASS   : tst_ExpectFail::initTestCase()
QDEBUG : tst_ExpectFail::xfailAndContinue() begin
XFAIL  : tst_ExpectFail::xfailAndContinue() This should xfail
   Loc: [/home/user/dev/qt5/qtbase/tests/auto/testlib/selftests/expectfail/tst_expectfail.cpp(70)]
QDEBUG : tst_ExpectFail::xfailAndContinue() after
PASS   : tst_ExpectFail::xfailAndContinue()
QDEBUG : tst_ExpectFail::xfailAndAbort() begin
XFAIL  : tst_ExpectFail::xfailAndAbort() This should xfail
   Loc: [/home/user/dev/qt5/qtbase/tests/auto/testlib/selftests/expectfail/tst_expectfail.cpp(78)]
PASS   : tst_ExpectFail::xfailAndAbort()
FAIL!  : tst_ExpectFail::xfailTwice() Already expecting a fail
   Loc: [/home/user/dev/qt5/qtbase/tests/auto/testlib/selftests/expectfail/tst_expectfail.cpp(88)]
XFAIL  : tst_ExpectFail::xfailWithQString() A string
   Loc: [/home/user/dev/qt5/qtbase/tests/auto/testlib/selftests/expectfail/tst_expectfail.cpp(97)]
XFAIL  : tst_ExpectFail::xfailWithQString() Bug 5 (The message)
   Loc: [/home/user/dev/qt5/qtbase/tests/auto/testlib/selftests/expectfail/tst_expectfail.cpp(102)]
PASS   : tst_ExpectFail::xfailWithQString()
XFAIL  : tst_ExpectFail::xfailDataDriven(Abort) This test should xfail
   Loc: [/home/user/dev/qt5/qtbase/tests/auto/testlib/selftests/expectfail/tst_expectfail.cpp(131)]
XFAIL  : tst_ExpectFail::xfailDataDriven(Continue) This test should xfail
   Loc: [/home/user/dev/qt5/qtbase/tests/auto/testlib/selftests/expectfail/tst_expectfail.cpp(131)]
PASS   : tst_ExpectFail::xfailDataDriven()
PASS   : tst_ExpectFail::xfailOnWrongRow()
XFAIL  : tst_ExpectFail::xfailOnAnyRow(first row) This test should xfail
   Loc: [/home/user/dev/qt5/qtbase/tests/auto/testlib/selftests/expectfail/tst_expectfail.cpp(166)]
XFAIL  : tst_ExpectFail::xfailOnAnyRow(second row) This test should xfail
   Loc: [/home/user/dev/qt5/qtbase/tests/auto/testlib/selftests/expectfail/tst_expectfail.cpp(166)]
PASS   : tst_ExpectFail::xfailOnAnyRow()
XPASS  : tst_ExpectFail::xpass() 'true' returned FALSE. ()
   Loc: [/home/user/dev/qt5/qtbase/tests/auto/testlib/selftests/expectfail/tst_expectfail.cpp(172)]
PASS   : tst_ExpectFail::cleanupTestCase()
Totals: 8 passed, 2 failed, 0 skipped
********* Finished testing of tst_ExpectFail *********
